### ISSUE TITLE
Creating a new study

### ISSUE THREAD

**Issue by ModeratelyGreek** [2E-arly/emerald-code-sparks#1]
- [x] Be able to Input study information (i.e. name, description, tags)
- [x] Be able to browse and Add students to the study by searching their names
- [x] Be able to search and add tags to the study.

Acceptance Criteria: As a researcher, I want a study creation form that allows me to declare study details in a centralized manner. The form should include fields for all necessary study details

<img width="662" alt="Screenshot 2023-10-26 at 3 36 51 PM" src="https://github.com/2E-arly/emerald-code-sparks/assets/49487996/ef05289d-c3eb-435d-9f20-c01e2cf53083">

**9 hours**

**Comment by ModeratelyGreek** [comment]
test

**Comment by cpeddireddyy** [comment]
**Updated Req for Sprint 2**

- [x] Implement Backend with Study Objects in Strapi [12]
- [x] Functionality Testing [4]

**Comment by cpeddireddyy** [comment]
**Updated Req for Sprint 2 (Pt. 2)**

- [x] Implement Search (Student & Tags) with GET request 
- [x] Create Study Object with POST request

**Comment by cpeddireddyy** [comment]
closing see branch [chaitra](https://github.com/2E-arly/emerald-code-sparks/tree/chaitra)
