### ISSUE TITLE
Study Data Consent Interface

### ISSUE THREAD

**Issue by ClaudioGSDB** [2E-arly/emerald-code-sparks#10]
Dynamic control of student's own consent to data collection.

Acceptance Criteria: Researcher should be able to easily customize and configure the data collection process as needed for different studies.

**9 hours**

**Comment by cpeddireddyy** [comment]
**Updated Req for Sprint 2**

- [x] Frontend Interface [8]
- [x] Strapi email handling [10]
- [x] User/ Type Verification [4]

**Comment by cpeddireddyy** [comment]
Researchers can specify data collection when creating study, issue completed from researcher  view
