### ISSUE TITLE
Tagging system

### ISSUE THREAD

**Issue by ClaudioGSDB** [2E-arly/emerald-code-sparks#2]
Tag system component that is called from different pages (i.e. main page, view study, create study)

- [x] Make a structure that stores all the projects and is searchable by tags

Acceptance Criteria: As a researcher, I want a tagging system in place that allows me to browse and tag entire classrooms into studies. Tags should be easily visible and searchable. 

**9 hours**

**Comment by cpeddireddyy** [comment]
**Updated Req for Sprint 2**

- [x] Merge into [Sprint-1](https://github.com/2E-arly/emerald-code-sparks/tree/sprint-1) [2]
- [x] Refactor into "Main Page" [3.5]
- [x] Refactor into "Create New Study Page" [3.5]

**Comment by cpeddireddyy** [comment]
Using predefined study tags to tag studies
