### ISSUE TITLE
Add researcher

### ISSUE THREAD

**Issue by ClaudioGSDB** [2E-arly/emerald-code-sparks#8]
Be able to invite other researchers to observe study results

Acceptance Criteria 

- [ ] Verify invited researcher has access to study information

**9 hours**

**Comment by cpeddireddyy** [comment]
**Updated Req for Sprint 2**

- [x] Strapi email handling [11]
- [x] User/ Type Verification [5]
- [x] Refactor into "Main Page" [2]

**Comment by cpeddireddyy** [comment]
Updated Req for Sprint 2 (Pt. 2)

- [x] Update access with POST request

**Comment by cpeddireddyy** [comment]
closing see branch [chaitra](https://github.com/2E-arly/emerald-code-sparks/tree/chaitra)
