### ISSUE TITLE
Researcher Main Page

### ISSUE THREAD

**Issue by ClaudioGSDB** [2E-arly/emerald-code-sparks#9]
Acceptance Criteria: Researchers should be able to view all of their studies, open individual study pages, etc.

**Comment by ModeratelyGreek** [comment]
Need to finish creating dummy data in STRAPI
Data objects are created though and soon will model the required features we want researchers to be able to observe.

**Comment by cpeddireddyy** [comment]
**Updated Req for Sprint 2**

- [x] Error Handling [10]
- [x] Merge into [Sprint-1](https://github.com/2E-arly/emerald-code-sparks/tree/sprint-1)
- [x] Functionality testing/ compatibility with Study Object [4]

**Comment by cpeddireddyy** [comment]
closing see branch [chaitra](https://github.com/2E-arly/emerald-code-sparks/tree/chaitra)
